version: '3.3'
services:

  frontend:
    container_name: front
    image: sokolnikovbogdan/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend
    image: sokolnikovbogdan/foodgram_back:latest
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/redoc/
      - static_value:/var/html/static/
      - media_value:/var/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  postgres_data:
